services:
  postgres:
      image: postgres:15
      container_name: postgres
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:${POSTGRES_PORT}"
      volumes:
        - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    volumes:
      - minio_data:/data

  file-service:
    build:
      context: .
      dockerfile: backend/file-service/Dockerfile
    env_file:
      - .env
    image: file-service:local
    container_name: file-service
    depends_on:
      - postgres
      - minio
    ports:
      - "8081:${FILE_SERVICE_PORT}"

  directory-service:
    build:
      context: .
      dockerfile: backend/directory-service/Dockerfile
    env_file:
      - .env
    image: directory-service:local
    container_name: directory-service
    depends_on:
      - postgres
    ports:
      - "8082:${DIRECTORY_SERVICE_PORT}"

  user-service:
    build:
      context: .
      dockerfile: backend/user-service/Dockerfile
    env_file:
      - .env
    image: user-service:local
    container_name: user-service
    depends_on:
      - postgres
    ports:
      - "8083:${USER_SERVICE_PORT}"

volumes:
  postgres_data:
  minio_data:
