server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;

        # важно для React Router - иначе не работает маршрутизация. Не проверено.
        try_files $uri /index.html;
    }
}